### ISSUE TITLE
find and findOne not working as expected.

### ISSUE THREAD

**Issue by Rud156** [quen2404/mongo-gridfs#2]
I'm trying to use GridFS using this library based on https://github.com/nestjs/nest/issues/1169#issuecomment-427792871 example that you had provided. 

The basics work. But when I'm using `find` or `findOne`, these always return `null` or errors out saying that no file was found.

I tried a simple query like `findOne({ _id: '<someValidId>' })`. This does not work but putting the same id in `findById('<someValidId>')` works.

#### Edit:
Works only when I send in parsed ObjectId and not raw strings

**Comment by quen2404** [comment]
Ok, thank you for your feedback.
